version: "2.0"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network
  monkeys:
    build:
      context: .
      dockerfile: Dockerfile
    image: alnair.red/ubuntu
    container_name: monkeys
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: monkeys
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       #- /var/www/node_modules
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
