version: "2.0"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network
  monkeys:
    build:
      context: .
      dockerfile: Dockerfile
    image: alnair.red/ubuntu
    container_name: monkeys
    restart: unless-stopped
    tty: true
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_DB: admin
      S3BUCKET: odavi-mongo-dumps
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
